L=[
  { 'FirstName': 'Noel', 'LastName': 'O.', 'Country': 'Albania', 'Continent': 'Europe', 'Age': 23, 'Language': 'Python' },
  { 'FirstName': 'Fatima', 'LastName': 'A.', 'Country': 'Algeria', 'Continent': 'Africa', 'Age': 25, 'Language': 'JavaScript' },
  { 'FirstName': 'Laia', 'LastName': 'P.', 'Country': 'Andorra', 'Continent': 'Europe', 'Age': 55, 'Language': 'Ruby' },
  { 'FirstName': 'Sofia', 'LastName': 'I.', 'Country': 'Argentina', 'Continent': 'Americas', 'Age': 35, 'Language': 'Java' },
  { 'FirstName': 'Nareh', 'LastName': 'Q.', 'Country': 'Armenia', 'Continent': 'Europe', 'Age': 80, 'Language': 'Clojure' },
  { 'FirstName': 'Daniel', 'LastName': 'J.', 'Country': 'Aruba', 'Continent': 'Americas', 'Age': 42, 'Language': 'JavaScript' },
  { 'FirstName': 'Oliver', 'LastName': 'Q.', 'Country': 'Australia', 'Continent': 'Oceania', 'Age': 69, 'Language': 'PHP' },
  { 'FirstName': 'Lukas', 'LastName': 'R.', 'Country': 'Austria', 'Continent': 'Europe', 'Age': 89, 'Language': 'C' },
  { 'FirstName': 'Zahra', 'LastName': 'S.', 'Country': 'Azerbaijan', 'Continent': 'Europe', 'Age': 22, 'Language': 'Java' },
  { 'FirstName': 'Kseniya', 'LastName': 'T.', 'Country': 'Belarus', 'Continent': 'Europe', 'Age': 29, 'Language': 'JavaScript' },
  { 'FirstName': 'Emma', 'LastName': 'U.', 'Country': 'Belgium', 'Continent': 'Europe', 'Age': 39, 'Language': 'Python' },
  { 'FirstName': 'Amar', 'LastName': 'V.', 'Country': 'Bosnia and Herzegovina', 'Continent': 'Europe', 'Age': 32, 'Language': 'Ruby' },
  { 'FirstName': 'Harry', 'LastName': 'K.', 'Country': 'Brazil', 'Continent': 'Americas', 'Age': 19, 'Language': 'Python' },
  { 'FirstName': 'Viktoria', 'LastName': 'W.', 'Country': 'Bulgaria', 'Continent': 'Europe', 'Age': 98, 'Language': 'PHP' },
  { 'FirstName': 'Thomas', 'LastName': 'L.', 'Country': 'Canada', 'Continent': 'Americas', 'Age': 38, 'Language': 'Java' },
  { 'FirstName': 'Agustin', 'LastName': 'M.', 'Country': 'Chile', 'Continent': 'Americas', 'Age': 37, 'Language': 'C' },
  { 'FirstName': 'Jing', 'LastName': 'X.', 'Country': 'China', 'Continent': 'Asia', 'Age': 39, 'Language': 'Ruby' },
  { 'FirstName': 'Marian', 'LastName': 'N.', 'Country': 'Colombia', 'Continent': 'Americas', 'Age': 55, 'Language': 'Python' },
  { 'FirstName': 'Lukas', 'LastName': 'X.', 'Country': 'Croatia', 'Continent': 'Europe', 'Age': 75, 'Language': 'Python' },
  { 'FirstName': 'Maria', 'LastName': 'Y.', 'Country': 'Cyprus', 'Continent': 'Europe', 'Age': 30, 'Language': 'Java' },
  { 'FirstName': 'Jakub', 'LastName': 'Z.', 'Country': 'Czech Republic', 'Continent': 'Europe', 'Age': 42, 'Language': 'Java' },
  { 'FirstName': 'Sofia', 'LastName': 'A.', 'Country': 'Denmark', 'Continent': 'Europe', 'Age': 19, 'Language': 'Python' },
  { 'FirstName': 'Mariam', 'LastName': 'B.', 'Country': 'Egypt', 'Continent': 'Africa', 'Age': 89, 'Language': 'Python' },
  { 'FirstName': 'George', 'LastName': 'B.', 'Country': 'England', 'Continent': 'Europe', 'Age': 21, 'Language': 'C' },
  { 'FirstName': 'Manuel', 'LastName': 'C.', 'Country': 'Equatorial Guinea', 'Continent': 'Africa', 'Age': 22, 'Language': 'Ruby' },
  { 'FirstName': 'Sofia', 'LastName': 'C.', 'Country': 'Estonia', 'Continent': 'Europe', 'Age': 29, 'Language': 'PHP' },
  { 'FirstName': 'Liam', 'LastName': 'D.', 'Country': 'Faroe Islands', 'Continent': 'Europe', 'Age': 28, 'Language': 'Python' },
  { 'FirstName': 'Ellen', 'LastName': 'E.', 'Country': 'Finland', 'Continent': 'Europe', 'Age': 55, 'Language': 'Ruby' },
  { 'FirstName': 'Louise', 'LastName': 'F.', 'Country': 'France', 'Continent': 'Europe', 'Age': 22, 'Language': 'Java' },
  { 'FirstName': 'Mariami', 'LastName': 'G.', 'Country': 'Georgia', 'Continent': 'Europe', 'Age': 29, 'Language': 'Python' },
  { 'FirstName': 'Mia', 'LastName': 'H.', 'Country': 'Germany', 'Continent': 'Europe', 'Age': 39, 'Language': 'Ruby' },
  { 'FirstName': 'Maria', 'LastName': 'I.', 'Country': 'Greece', 'Continent': 'Europe', 'Age': 32, 'Language': 'C' },
  { 'FirstName': 'Malik', 'LastName': 'J.', 'Country': 'Greenland', 'Continent': 'Europe', 'Age': 19, 'Language': 'Python' },
  { 'FirstName': 'Chloe', 'LastName': 'K.', 'Country': 'Guernsey', 'Continent': 'Europe', 'Age': 88, 'Language': 'Ruby' },
  { 'FirstName': 'Stevenson', 'LastName': 'O.', 'Country': 'Haiti', 'Continent': 'Americas', 'Age': 22, 'Language': 'Ruby' },
  { 'FirstName': 'Hanna', 'LastName': 'L.', 'Country': 'Hungary', 'Continent': 'Europe', 'Age': 29, 'Language': 'JavaScript' },
  { 'FirstName': 'Margret', 'LastName': 'M.', 'Country': 'Iceland', 'Continent': 'Europe', 'Age': 28, 'Language': 'Java' },
  { 'FirstName': 'Aadya', 'LastName': 'Y.', 'Country': 'India', 'Continent': 'Asia', 'Age': 29, 'Language': 'PHP' },
  { 'FirstName': 'Fatemeh', 'LastName': 'Z.', 'Country': 'Iran', 'Continent': 'Asia', 'Age': 29, 'Language': 'Java' },
  { 'FirstName': 'Emily', 'LastName': 'N.', 'Country': 'Ireland', 'Continent': 'Europe', 'Age': 98, 'Language': 'Ruby' },
  { 'FirstName': 'Joshua', 'LastName': 'O.', 'Country': 'Isle of Man', 'Continent': 'Europe', 'Age': 39, 'Language': 'Clojure' },
  { 'FirstName': 'Noa', 'LastName': 'A.', 'Country': 'Israel', 'Continent': 'Asia', 'Age': 40, 'Language': 'Ruby' },
  { 'FirstName': 'Sofia', 'LastName': 'P.', 'Country': 'Italy', 'Continent': 'Europe', 'Age': 71, 'Language': 'Clojure' },
  { 'FirstName': 'Jayden', 'LastName': 'P.', 'Country': 'Jamaica', 'Continent': 'Americas', 'Age': 42, 'Language': 'JavaScript' },
  { 'FirstName': 'Sou', 'LastName': 'B.', 'Country': 'Japan', 'Continent': 'Asia', 'Age': 43, 'Language': 'PHP' },
  { 'FirstName': 'Rimas', 'LastName': 'C.', 'Country': 'Jordan', 'Continent': 'Asia', 'Age': 44, 'Language': 'Java' },
  { 'FirstName': 'Yerasyl', 'LastName': 'D.', 'Country': 'Kazakhstan', 'Continent': 'Asia', 'Age': 22, 'Language': 'Ruby' },
  { 'FirstName': 'Sofija', 'LastName': 'Q.', 'Country': 'Latvia', 'Continent': 'Europe', 'Age': 29, 'Language': 'Ruby' },
  { 'FirstName': 'Aya', 'LastName': 'D.', 'Country': 'Libya', 'Continent': 'Africa', 'Age': 39, 'Language': 'C' },
  { 'FirstName': 'Anna', 'LastName': 'R.', 'Country': 'Liechtenstein', 'Continent': 'Europe', 'Age': 32, 'Language': 'JavaScript' },
  { 'FirstName': 'Emilija', 'LastName': 'S.', 'Country': 'Lithuania', 'Continent': 'Europe', 'Age': 19, 'Language': 'Python' },
  { 'FirstName': 'Gabriel', 'LastName': 'T.', 'Country': 'Luxembourg', 'Continent': 'Europe', 'Age': 28, 'Language': 'Java' },
  { 'FirstName': 'Nor', 'LastName': 'E.', 'Country': 'Malaysia', 'Continent': 'Asia', 'Age': 21, 'Language': 'Clojure' },
  { 'FirstName': 'Mamadou', 'LastName': 'E.', 'Country': 'Mali', 'Continent': 'Africa', 'Age': 22, 'Language': 'Python' },
  { 'FirstName': 'Luke', 'LastName': 'V.', 'Country': 'Malta', 'Continent': 'Europe', 'Age': 129, 'Language': 'PHP' },
  { 'FirstName': 'Ximena', 'LastName': 'Q.', 'Country': 'Mexico', 'Continent': 'Americas', 'Age': 28, 'Language': 'Java' },
  { 'FirstName': 'Sofia', 'LastName': 'W.', 'Country': 'Moldova', 'Continent': 'Europe', 'Age': 29, 'Language': 'Ruby' },
  { 'FirstName': 'Gabriel', 'LastName': 'X.', 'Country': 'Monaco', 'Continent': 'Europe', 'Age': 79, 'Language': 'PHP' },
  { 'FirstName': 'Odval', 'LastName': 'F.', 'Country': 'Mongolia', 'Continent': 'Asia', 'Age': 38, 'Language': 'Python' },
  { 'FirstName': 'Sara', 'LastName': 'Y.', 'Country': 'Montenegro', 'Continent': 'Europe', 'Age': 39, 'Language': 'C' },
  { 'FirstName': 'Mohamed', 'LastName': 'F.', 'Country': 'Morocco', 'Continent': 'Africa', 'Age': 90, 'Language': 'Ruby' },
  { 'FirstName': 'Krishna', 'LastName': 'G.', 'Country': 'Nepal', 'Continent': 'Asia', 'Age': 112, 'Language': 'Java' },
  { 'FirstName': 'Emma', 'LastName': 'Z.', 'Country': 'Netherlands', 'Continent': 'Europe', 'Age': 29, 'Language': 'Ruby' },
  { 'FirstName': 'Nikau', 'LastName': 'R.', 'Country': 'New Zealand', 'Continent': 'Oceania', 'Age': 39, 'Language': 'Ruby' },
  { 'FirstName': 'Emily', 'LastName': 'A.', 'Country': 'Northern Ireland', 'Continent': 'Europe', 'Age': 32, 'Language': 'JavaScript' },
  { 'FirstName': 'Emma', 'LastName': 'B.', 'Country': 'Norway', 'Continent': 'Europe', 'Age': 19, 'Language': 'Clojure' },
  { 'FirstName': 'Fatima', 'LastName': 'H.', 'Country': 'Pakistan', 'Continent': 'Asia', 'Age': 8, 'Language': 'JavaScript' },
  { 'FirstName': 'Ramon', 'LastName': 'R.', 'Country': 'Paraguay', 'Continent': 'Americas', 'Age': 99, 'Language': 'Ruby' },
  { 'FirstName': 'Maria', 'LastName': 'S.', 'Country': 'Peru', 'Continent': 'Americas', 'Age': 60, 'Language': 'C' },
  { 'FirstName': 'Althea', 'LastName': 'I.', 'Country': 'Philippines', 'Continent': 'Asia', 'Age': 81, 'Language': 'Python' },
  { 'FirstName': 'Piotr', 'LastName': 'B.', 'Country': 'Poland', 'Continent': 'Europe', 'Age': 128, 'Language': 'JavaScript' },
  { 'FirstName': 'Joao', 'LastName': 'D.', 'Country': 'Portugal', 'Continent': 'Europe', 'Age': 65, 'Language': 'JavaScript' },
  { 'FirstName': 'Victoria', 'LastName': 'T.', 'Country': 'Puerto Rico', 'Continent': 'Americas', 'Age': 70, 'Language': 'Python' },
  { 'FirstName': 'Marija', 'LastName': 'U.', 'Country': 'Republic of Macedonia', 'Continent': 'Europe', 'Age': 42, 'Language': 'JavaScript' },
  { 'FirstName': 'Andrei', 'LastName': 'E.', 'Country': 'Romania', 'Continent': 'Europe', 'Age': 59, 'Language': 'C' },
  { 'FirstName': 'Alexander', 'LastName': 'F.', 'Country': 'Russia', 'Continent': 'Europe', 'Age': 89, 'Language': 'Java' },
  { 'FirstName': 'Fatima', 'LastName': 'K.', 'Country': 'Saudi Arabia', 'Continent': 'Asia', 'Age': 105, 'Language': 'Clojure' },
  { 'FirstName': 'Mark', 'LastName': 'G.', 'Country': 'Scotland', 'Continent': 'Europe', 'Age': 52, 'Language': 'JavaScript' },
  { 'FirstName': 'Nikola', 'LastName': 'H.', 'Country': 'Serbia', 'Continent': 'Europe', 'Age': 29, 'Language': 'Python' },
  { 'FirstName': 'Jakub', 'LastName': 'I.', 'Country': 'Slovakia', 'Continent': 'Europe', 'Age': 28, 'Language': 'Java' },
  { 'FirstName': 'Luka', 'LastName': 'J.', 'Country': 'Slovenia', 'Continent': 'Europe', 'Age': 39, 'Language': 'Clojure' },
  { 'FirstName': 'Precious', 'LastName': 'G.', 'Country': 'South Africa', 'Continent': 'Africa', 'Age': 22, 'Language': 'JavaScript' },
  { 'FirstName': 'Seoyeon', 'LastName': 'J.', 'Country': 'South Korea', 'Continent': 'Asia', 'Age': 29, 'Language': 'Ruby' },
  { 'FirstName': 'Hugo', 'LastName': 'K.', 'Country': 'Spain', 'Continent': 'Europe', 'Age': 39, 'Language': 'Python' },
  { 'FirstName': 'William', 'LastName': 'L.', 'Country': 'Sweden', 'Continent': 'Europe', 'Age': 32, 'Language': 'Java' },
  { 'FirstName': 'Noah', 'LastName': 'M.', 'Country': 'Switzerland', 'Continent': 'Europe', 'Age': 19, 'Language': 'C' },
  { 'FirstName': 'Maia', 'LastName': 'S.', 'Country': 'Tahiti', 'Continent': 'Oceania', 'Age': 28, 'Language': 'Clojure' },
  { 'FirstName': 'Shufen', 'LastName': 'L.', 'Country': 'Taiwan', 'Continent': 'Asia', 'Age': 35, 'Language': 'PHP' },

  { 'FirstName': 'Mehdi', 'LastName': 'H.', 'Country': 'Tunisia', 'Continent': 'Africa', 'Age': 42, 'Language': 'Python' },
  { 'FirstName': 'Yusuf', 'LastName': 'N.', 'Country': 'Turkey', 'Continent': 'Europe', 'Age': 22, 'Language': 'Python' },
  { 'FirstName': 'Artem', 'LastName': 'O.', 'Country': 'Ukraine', 'Continent': 'Europe', 'Age': 29, 'Language': 'Java' },
  { 'FirstName': 'Mohammad', 'LastName': 'N.', 'Country': 'United Arab Emirates', 'Continent': 'Asia', 'Age': 39, 'Language': 'C' },
  { 'FirstName': 'Agustin', 'LastName': 'V.', 'Country': 'Uruguay', 'Continent': 'Americas', 'Age': 19, 'Language': 'JavaScript' },
  { 'FirstName': 'Sebastian', 'LastName': 'W.', 'Country': 'Venezuela', 'Continent': 'Americas', 'Age': 8, 'Language': 'Python' },
  { 'FirstName': 'Oliver', 'LastName': 'P.', 'Country': 'Wales', 'Continent': 'Europe', 'Age': 69, 'Language': 'JavaScript' },
  {'FirstName': 'Jaume', 'LastName': 'R.', 'Country': 'Andorra', 'Continent': 'Europe', 'Age': 112, 'Language': 'COBOL'},
  {'FirstName': 'Akar', 'LastName': 'L.', 'Country': 'Tibet', 'Continent': 'Asia', 'Age': 92, 'Language': 'COBOL'},
  {'FirstName': 'Alexei', 'LastName': 'N.', 'Country': 'Russia', 'Continent': 'Europe', 'Age': 78, 'Language': 'COBOL'},
  {'FirstName': 'Dorothy', 'LastName': 'Z.', 'Country': 'Belgium', 'Continent': 'Europe', 'Age': 84, 'Language': 'COBOL'},
  {'FirstName': 'Mswati', 'LastName': 'P.', 'Country': 'Eswatini', 'Continent': 'Africa', 'Age': 3, 'Language': 'COBOL'},
  {'FirstName': 'Donald', 'LastName': 'T.', 'Country': 'United States of America', 'Continent': 'Americas', 'Age': 77, 'Language': 'COBOL'},
]


#for i,d in enumerate(L,5):
#        print(f"""          03  dev{i}.
#              05 FirstName    pic a(9)  value '{d['FirstName']}'.
#              05 LastName     pic x(2)  value '{d['LastName']}'.
#              05 Country      pic a(24) value '{d['Country']}'.
#              05 Continent    pic a(8)  value '{d['Continent']}'.
#              05 Age          pic 9(3)  value {d['Age']}.
#              05 Language     pic a(10) value '{d['Language']}'.""")
i=0
for d in L:
    if d['FirstName']=='Sofia':
        print(f"""          03  .
              05 FirstName    pic a(9)  value '{d['FirstName']}'.
              05 LastName     pic x(2)  value '{d['LastName']}'.
              05 Country      pic a(24) value '{d['Country']}'.
              05 Continent    pic a(8)  value '{d['Continent']}'.
              05 Age          pic 9(3)  value {d['Age']}.
              05 Language     pic a(10) value '{d['Language']}'.""")
